version: '3.8'

services:
  pubg_report:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: ${BUILD_CONFIGURATION:-Release}
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs # Example of how to map a local directory to the container
    entrypoint: ["dotnet", "PubgReportCrawler.dll"]
